// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "order/order.proto" (package "order", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { OrderService } from "./order";
import type { UpdateOrderStatusResponse } from "./order";
import type { UpdateOrderStatusRequest } from "./order";
import type { DetailOrderResponse } from "./order";
import type { DetailOrderRequest } from "./order";
import type { ListOrderResponse } from "./order";
import type { ListOrderRequest } from "./order";
import type { ListOrderAdminResponse } from "./order";
import type { ListOrderAdminRequest } from "./order";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateOrderResponse } from "./order";
import type { CreateOrderRequest } from "./order";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service order.OrderService
 */
export interface IOrderServiceClient {
    /**
     * @generated from protobuf rpc: CreateOrder(order.CreateOrderRequest) returns (order.CreateOrderResponse);
     */
    createOrder(input: CreateOrderRequest, options?: RpcOptions): UnaryCall<CreateOrderRequest, CreateOrderResponse>;
    /**
     * @generated from protobuf rpc: ListOrderAdmin(order.ListOrderAdminRequest) returns (order.ListOrderAdminResponse);
     */
    listOrderAdmin(input: ListOrderAdminRequest, options?: RpcOptions): UnaryCall<ListOrderAdminRequest, ListOrderAdminResponse>;
    /**
     * @generated from protobuf rpc: ListOrder(order.ListOrderRequest) returns (order.ListOrderResponse);
     */
    listOrder(input: ListOrderRequest, options?: RpcOptions): UnaryCall<ListOrderRequest, ListOrderResponse>;
    /**
     * @generated from protobuf rpc: DetailOrder(order.DetailOrderRequest) returns (order.DetailOrderResponse);
     */
    detailOrder(input: DetailOrderRequest, options?: RpcOptions): UnaryCall<DetailOrderRequest, DetailOrderResponse>;
    /**
     * @generated from protobuf rpc: UpdateOrderStatus(order.UpdateOrderStatusRequest) returns (order.UpdateOrderStatusResponse);
     */
    updateOrderStatus(input: UpdateOrderStatusRequest, options?: RpcOptions): UnaryCall<UpdateOrderStatusRequest, UpdateOrderStatusResponse>;
}
/**
 * @generated from protobuf service order.OrderService
 */
export class OrderServiceClient implements IOrderServiceClient, ServiceInfo {
    typeName = OrderService.typeName;
    methods = OrderService.methods;
    options = OrderService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateOrder(order.CreateOrderRequest) returns (order.CreateOrderResponse);
     */
    createOrder(input: CreateOrderRequest, options?: RpcOptions): UnaryCall<CreateOrderRequest, CreateOrderResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateOrderRequest, CreateOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListOrderAdmin(order.ListOrderAdminRequest) returns (order.ListOrderAdminResponse);
     */
    listOrderAdmin(input: ListOrderAdminRequest, options?: RpcOptions): UnaryCall<ListOrderAdminRequest, ListOrderAdminResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListOrderAdminRequest, ListOrderAdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListOrder(order.ListOrderRequest) returns (order.ListOrderResponse);
     */
    listOrder(input: ListOrderRequest, options?: RpcOptions): UnaryCall<ListOrderRequest, ListOrderResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListOrderRequest, ListOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailOrder(order.DetailOrderRequest) returns (order.DetailOrderResponse);
     */
    detailOrder(input: DetailOrderRequest, options?: RpcOptions): UnaryCall<DetailOrderRequest, DetailOrderResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailOrderRequest, DetailOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateOrderStatus(order.UpdateOrderStatusRequest) returns (order.UpdateOrderStatusResponse);
     */
    updateOrderStatus(input: UpdateOrderStatusRequest, options?: RpcOptions): UnaryCall<UpdateOrderStatusRequest, UpdateOrderStatusResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateOrderStatusRequest, UpdateOrderStatusResponse>("unary", this._transport, method, opt, input);
    }
}
